// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPrompt(arg1) {
  return window['go']['main']['App']['AddPrompt'](arg1);
}

export function AddPromptBatch(arg1) {
  return window['go']['main']['App']['AddPromptBatch'](arg1);
}

export function CloseBrowser() {
  return window['go']['main']['App']['CloseBrowser']();
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DetectChromePath() {
  return window['go']['main']['App']['DetectChromePath']();
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetBrowserInfo() {
  return window['go']['main']['App']['GetBrowserInfo']();
}

export function GetBrowserStatus() {
  return window['go']['main']['App']['GetBrowserStatus']();
}

export function GetCredits() {
  return window['go']['main']['App']['GetCredits']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetQueueStatus() {
  return window['go']['main']['App']['GetQueueStatus']();
}

export function GetSelectors() {
  return window['go']['main']['App']['GetSelectors']();
}

export function GetTasksByStatus(arg1) {
  return window['go']['main']['App']['GetTasksByStatus'](arg1);
}

export function ImportPromptsFromFile() {
  return window['go']['main']['App']['ImportPromptsFromFile']();
}

export function LaunchBrowser() {
  return window['go']['main']['App']['LaunchBrowser']();
}

export function PauseQueue() {
  return window['go']['main']['App']['PauseQueue']();
}

export function RefreshAPIToken() {
  return window['go']['main']['App']['RefreshAPIToken']();
}

export function RequeueTask(arg1) {
  return window['go']['main']['App']['RequeueTask'](arg1);
}

export function ResumeQueue() {
  return window['go']['main']['App']['ResumeQueue']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartQueue() {
  return window['go']['main']['App']['StartQueue']();
}

export function StopQueue() {
  return window['go']['main']['App']['StopQueue']();
}

export function UpdateAppConfig(arg1) {
  return window['go']['main']['App']['UpdateAppConfig'](arg1);
}

export function UpdateSelector(arg1, arg2) {
  return window['go']['main']['App']['UpdateSelector'](arg1, arg2);
}
