// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {config} from '../models';
import {chrome} from '../models';
import {api} from '../models';

export function AddPrompt(arg1:string):Promise<storage.Task>;

export function AddPromptBatch(arg1:Array<string>):Promise<number>;

export function CloseBrowser():Promise<void>;

export function CreateTask(arg1:string):Promise<storage.Task>;

export function DeleteTask(arg1:number):Promise<void>;

export function DetectChromePath():Promise<string>;

export function GetAllTasks():Promise<Array<storage.Task>>;

export function GetAppConfig():Promise<config.AppConfig>;

export function GetBrowserInfo():Promise<chrome.BrowserInfo>;

export function GetBrowserStatus():Promise<string>;

export function GetCredits():Promise<api.CreditsResponse>;

export function GetDashboardStats():Promise<storage.Stats>;

export function GetQueueStatus():Promise<string>;

export function GetSelectors():Promise<Record<string, string>>;

export function GetTasksByStatus(arg1:string):Promise<Array<storage.Task>>;

export function ImportPromptsFromFile():Promise<number>;

export function LaunchBrowser():Promise<void>;

export function PauseQueue():Promise<void>;

export function RefreshAPIToken():Promise<void>;

export function RequeueTask(arg1:number):Promise<void>;

export function ResumeQueue():Promise<void>;

export function SelectDirectory():Promise<string>;

export function StartQueue():Promise<void>;

export function StopQueue():Promise<void>;

export function UpdateAppConfig(arg1:config.AppConfig):Promise<void>;

export function UpdateSelector(arg1:string,arg2:string):Promise<void>;
